### ISSUE TITLE
Set fan power manually

### ISSUE THREAD

**Issue by Leon3310** [Robbe-B/maestro_mcz#94]
Hello,

I've just downloaded the latest version and I see that you can now choose between "Auto" and "Silent" for the fans, but is there still a way to set the fan power manually from 1 to 5?

Thank you very much

**Comment by Robbe-B** [comment]
@Leon3310,

You can still use the speeds of the fans, but it's not defined as a preset anymore. 
Accordingly to the official Home Assistant documentation, defining a manual speeds as a preset is not allowed.
Instead the speed is now a percentage selectable in the correct step size for your stove model(see examples below).
You can now select either a preset (e.g. auto) or either a speed (e.g. 60%)
see official documentation for more information => https://developers.home-assistant.io/docs/core/entity/fan

![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/720de15d-fc31-413f-be9b-9f27168f55c3)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/fe097fd1-e2b3-4cc3-8046-62a8770d3677)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/adecbd3e-95d0-4b45-9cdc-59ac43544f6a)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/26ffe403-4c45-4dc6-afad-8ff49ca3cda8)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/5a2906f1-1699-4ade-8313-944b44059505)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/93899ec0-7d6f-46b4-97f7-c8b0d0038d77)

Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@Leon3310,
If you want the old MCZ style of fan speeds back, you can do something like this in your dashboard:
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/308f759e-deb6-4b5f-81e0-09e02b5447a1)
I can share it if you want :) 

Kind regards,
Robbe

**Comment by Leon3310** [comment]
Hello,

I have a lot of things in home assistant and these are my first "fans". I hadn't understood how it worked. In fact, everything works fine. Your dashboard is really cool. I'm very interested.

Thank you very much for all your work.

**Comment by Robbe-B** [comment]
@Leon3310,
This is some basic YAML , and obviously, you need to replace the entity name with the correct one for you.
Here you go:
```
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.turn_off
      target:
        entity_id:
          - fan.club_m2_fan_2
    entity: fan.club_m2_fan_2
    icon: mdi:fan-off
    name: 'Off'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_percentage
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        percentage: 20
    entity: fan.club_m2_fan_2
    icon: mdi:fan-speed-1
    name: '1'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_percentage
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        percentage: 40
    entity: fan.club_m2_fan_2
    icon: mdi:fan-speed-2
    name: '2'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_percentage
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        percentage: 60
    entity: fan.club_m2_fan_2
    icon: mdi:fan-speed-3
    name: '3'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_percentage
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        percentage: 80
    entity: fan.club_m2_fan_2
    icon: mdi:fan-chevron-up
    name: '4'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_percentage
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        percentage: 100
    entity: fan.club_m2_fan_2
    icon: mdi:fan-chevron-up
    name: '5'
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      target:
        entity_id:
          - fan.club_m2_fan_2
      data:
        preset_mode: auto
    entity: fan.club_m2_fan_2
    icon: mdi:fan-auto
    name: Auto
```

Kind regards,
Robbe
